import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import { InterviewProvider } from "@/lib/contexts/interview-context";

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.variable} antialiased`}>
        <InterviewProvider>{children}</InterviewProvider>
      </body>
    </html>
  );
}
